"""
ContentEvaluator -- Wiki auto-grow quality assessment.

Evaluates wiki content generated by Hermes Agent cron jobs against
quality dimensions and reports results to future-agi for visualization.
"""

import json
import logging
import os
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


# ── Quality dimensions ──────────────────────────────────────────────

DEFAULT_DIMENSIONS = [
    "accuracy",       # factual correctness
    "completeness",   # coverage of the topic
    "clarity",        # readability and structure
    "freshness",      # up-to-date information
    "relevance",      # alignment with wiki scope
    "actionability",  # practical utility
]


class ContentEvaluator:
    """
    Evaluates wiki content quality using an LLM-as-judge pattern.

    Sends evaluation results as spans to future-agi where they can be:
    - Visualized on dashboards
    - Compared across model variants
    - Used for automated content gating (approve/reject)

    Usage:
        evaluator = ContentEvaluator(model="gpt-4o-mini")
        result = evaluator.evaluate(
            wiki_url="/wiki/Python-AsyncIO",
            content="# AsyncIO\nPython asyncio is...",
            action="auto-grow",
            rubric={"accuracy": "Check for factual errors"}
        )
        # result: {"overall_score": 0.85, "dimensions": {"accuracy": 0.9, ...}}
    """

    def __init__(
        self,
        model: Optional[str] = None,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        tracer=None,
    ):
        self.model = model or os.getenv("HERMES_EVAL_MODEL", "gpt-4o-mini")
        self.api_key = api_key or os.getenv("OPENAI_API_KEY", "")
        self.base_url = base_url or os.getenv("HERMES_EVAL_BASE_URL")
        self.tracer = tracer
        self._client = None

    def _get_client(self):
        if self._client is None:
            from openai import OpenAI
            kwargs = {"api_key": self.api_key}
            if self.base_url:
                kwargs["base_url"] = self.base_url
            self._client = OpenAI(**kwargs)
        return self._client

    def evaluate(
        self,
        wiki_url: str,
        content: str,
        action: str = "auto-grow",
        rubric: Optional[Dict[str, str]] = None,
        dimensions: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """
        Evaluate wiki content quality.

        Args:
            wiki_url: The wiki page URL/path
            content: The content to evaluate
            action: "auto-grow", "update", "review"
            rubric: Custom rubric per dimension {dim: description}
            dimensions: List of dimensions to evaluate (defaults to DEFAULT_DIMENSIONS)

        Returns:
            Dict with overall_score (0-1) and per-dimension scores.
        """
        dims = dimensions or DEFAULT_DIMENSIONS
        rubric = rubric or {}

        # Build the evaluation prompt
        dim_criteria = []
        for d in dims:
            criteria = rubric.get(d, self._default_criteria(d))
            dim_criteria.append(f"- **{d}**: {criteria}")

        system_prompt = (
            "You are an expert wiki content evaluator. "
            "Score content on each dimension from 0.0 to 1.0. "
            "Return ONLY a JSON object with the scores."
        )

        user_prompt = (
            f"Evaluate the following wiki content.\n\n"
            f"Content:\n```\n{content[:4000]}\n```\n\n"
            f"Score each dimension:\n" + "\n".join(dim_criteria) + "\n\n"
            f"Return JSON: " + json.dumps({
                d: 0.85 for d in dims
            }, indent=2)
        )

        try:
            response = self._get_client().chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.0,
                response_format={"type": "json_object"},
                max_tokens=500,
            )
            raw = response.choices[0].message.content or "{}"
            scores = json.loads(raw)

            # Normalize and compute overall
            dimensions_scores = {}
            total = 0.0
            for d in dims:
                val = float(scores.get(d, scores.get(d.lower(), 0.5)))
                val = max(0.0, min(1.0, val))
                dimensions_scores[d] = round(val, 3)
                total += val
            overall = round(total / len(dims), 3) if dims else 0.0

            result = {
                "overall_score": overall,
                "dimensions": dimensions_scores,
                "wiki_url": wiki_url,
                "action": action,
                "model_used": self.model,
            }

            # Report to future-agi
            if self.tracer:
                self.tracer.record_wiki_quality(
                    wiki_url=wiki_url,
                    action=action,
                    content=content,
                    score=overall,
                    dimensions=dimensions_scores,
                    model=self.model,
                )

            return result

        except Exception as e:
            logger.error("Content evaluation failed: %s", e)
            return {
                "overall_score": 0.0,
                "dimensions": {d: 0.0 for d in dims},
                "error": str(e),
                "wiki_url": wiki_url,
                "action": action,
            }

    def evaluate_batch(
        self,
        items: List[Dict[str, str]],
        rubric: Optional[Dict[str, str]] = None,
    ) -> List[Dict[str, Any]]:
        """Evaluate multiple wiki pages in batch."""
        results = []
        for item in items:
            result = self.evaluate(
                wiki_url=item["wiki_url"],
                content=item["content"],
                action=item.get("action", "auto-grow"),
                rubric=rubric,
            )
            results.append(result)
        return results

    def is_acceptable(
        self,
        scores: Dict[str, Any],
        threshold: float = 0.7,
        min_dimensions: Optional[Dict[str, float]] = None,
    ) -> Tuple[bool, str]:
        """
        Check if content meets quality thresholds.

        Returns (is_acceptable, reason).
        """
        overall = scores.get("overall_score", 0)
        if overall < threshold:
            return False, f"Overall score {overall} below threshold {threshold}"

        dims = scores.get("dimensions", {})
        if min_dimensions:
            for dim, min_val in min_dimensions.items():
                actual = dims.get(dim, 0)
                if actual < min_val:
                    return False, f"{dim} score {actual} below minimum {min_val}"

        return True, f"Content acceptable (overall={overall})"

    @staticmethod
    def _default_criteria(dimension: str) -> str:
        criteria = {
            "accuracy": "Check for factual errors, incorrect claims, outdated information",
            "completeness": "Assess if the topic is covered comprehensively",
            "clarity": "Evaluate readability, structure, and organization",
            "freshness": "Check if information reflects current state of the topic",
            "relevance": "Assess alignment with wiki scope and audience",
            "actionability": "Evaluate if content provides practical, usable information",
        }
        return criteria.get(dimension, f"Evaluate the {dimension} of the content")
